### ISSUE TITLE
dock construction maybe unreasonable

### ISSUE THREAD

**Issue by dogdogbrother** [Adashuai5/my-desktop#1]
程序坞的宽度是由内部撑开的，这样当里面的程序大小改变时，整体也会有一个顺滑的动画过渡，现在会一蹦一卡和原生的macOS有明显的感知差距。

**Comment by Adashuai5** [comment]
非常对的建议，虽然我的思路是内部撑开，但是又设置了一遍宽度，这是没必要的，现在已经去掉。
